### ISSUE TITLE
Doesn't Shows the values...

### ISSUE THREAD

**Issue by madnitfo2** [plusCubed/velociraptor#18]
It always looks like that...

![screenshot_20160417-115703](https://cloud.githubusercontent.com/assets/14232298/14586285/cf65ae4c-0493-11e6-94d3-a3dc51e9eacf.png)

**Comment by plusCubed** [comment]
There are many reasons it could be like that. The most common reason is your area is not covered - can you check [here](http://goo.gl/tEjlbz)? If it is not covered, you can help add it on a computer on [OpenStreetMap's website.](http://openstreetmap.org). If your area IS covered and it shows that, I added debugging stats to 1.1.3 - once you receive the update, please turn that on and take a screenshot.

**Comment by madnitfo2** [comment]
![screenshot_20160422-155236](https://cloud.githubusercontent.com/assets/14232298/14743565/6949b712-08a2-11e6-9b85-cd6a8ffb0c98.png)

Yes this area is covered...
I hope it helps...

Looks like a nice app...

**Comment by plusCubed** [comment]
Yes, things have developed since my last response. The app is currently overwhelming the OpenStreetMap servers. I am talking to the server maintainer, but for now all requests from the app are blocked. I setting up separate servers to deal with the load as well, which should hopefully go up by the end of this week. Sorry for the inconvenience.
