### ISSUE TITLE
Remarks/suggestions after update

### ISSUE THREAD

**Issue by hoevenpe** [plusCubed/velociraptor#32]
First of all, thanks for the update. It looks nice!

A few things i noticed:

- Sound is played on media channel, this will be muted by default for a lot of people. Use alarm or system channel instead?

- Without Speed Limit information the sign is shown with '--' in it. Why not hide the sign to free up screen space?

- Is there some time issue with the speed limit data? Here we have time specific speed limits (100 6-19h, 130 otherwise) but they often are shown incorrect. Is this a problem in the Waze data?

- The gradient is a neat idea but to be honest of little use. During driving you are more than a meter from the phone screen, these small details will not be visible without losing focus on the road. Perhaps some other color combination: blue solid filled circle with digits in white, changing to solid red?

- Now we only get a single beep while speeding, why not repeat it until the speed is dropped or the icon is tapped? You can even make it 'intelligent': less pause between the beeps when the speeding increases (just like the beeps of reverse driving nearing an obstacle).

- Please increase the size of the current speed, its now not easily readable during driving. Make it bold and larger (other?) font just like in Google Maps. 

Just my 2ct... :-)

**Comment by techguyone** [comment]
Current speed needs to be the same size as the top circle speed. So the mph/kph needs to go (we know what it is because we set it in prefs we don't need it on screen)

The gradient is valueless, should be one colour for below or at speed limit & another for when  exceeded, that's it. 
People just aren't going to be staring at the screen to see the (mostly incomprehensible) gradient thing.
When you drive, everything you need to see needs to be accomplished in one swift glance.

**Comment by plusCubed** [comment]
@hoevenpe:
- In the current version it plays on the notification channel
- Created #50
- Created #51
- See #30 
- Created #52
- See #42 

@techguyone Created #53. See #30.
